name: Upload Assets

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and upload to s3 run on Node ${{ matrix.node }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Env variables
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_VITE_SHOPIFY_KEY: ${{ secrets.VITE_SHOPIFY_KEY }}

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
          node-version: ${{ matrix.node-version }}

    - name: Install NPM dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Deploy assets to S3 bucket
      run: aws s3 sync ./dist/assets/ s3://toda-delicadinha --delete